### ISSUE TITLE
Error on testing the docker installation

### ISSUE THREAD

**Issue by abinashmeher999** [shogun-toolbox/shogun-cloud#1]
After following the instructions from [here](https://docs.docker.com/installation/ubuntulinux/#ubuntu-trusty-1404-lts-64-bit), I installed the docker-maintained package for Ubuntu 14.04 LTS.
These were the instructions given to test the installation.

> To verify that everything has worked as expected:
> 
> `$ sudo docker run -i -t ubuntu /bin/bash`
> 
> Which should download the ubuntu image, and then start bash in a container.

After the command I get the following error

```
abinashmeher999@JARVIS:~$ sudo docker run -i -t ubuntu /bin/bash
[sudo] password for abinashmeher999:
Unable to find image 'ubuntu:latest' locally
Pulling repository ubuntu
FATA[0000] Get https://index.docker.io/v1/repositories/library/ubuntu/images: dial tcp 162.242.195.84:443: connection refused
abinashmeher999@JARVIS:~$ sudo -E docker run -i -t ubuntu /bin/bash
Unable to find image 'ubuntu:latest' locally
Pulling repository ubuntu
FATA[0000] Get https://index.docker.io/v1/repositories/library/ubuntu/images: dial tcp 162.242.195.84:443: connection refused 
```

I searched the internet but couldn't find any solution to the problem. I found a similar unanswered problem [here](https://askubuntu.com/questions/578870/docker-ubuntu-image-download-test-failed?newreg=aaf08b9cadc7432d95f0990c46faa43d).
Please suggest a workaround.

**Comment by bingzhux** [comment]
I got the same issue, do you have an idea to get it fixed?

**Comment by karlnapf** [comment]
@vigsterkr ?

**Comment by glenti** [comment]
You have to enable http_proxy and https_proxy environment variables in /etc/default/docker (setting your proxy ip and port). The example below is looking for local cntlm doing proxy authentication:

export http_proxy="http://127.0.0.1:3128/"
export https_proxy="http://127.0.0.1:3128/"

**Comment by anroots** [comment]
``` bash
DOCKER_OPTS="--dns 192.168.0.252 --dns 192.168.0.253 --dns 8.8.8.8 --dns 8.8.4.4"
HTTP_PROXY="http://cache.net.local:3128"
HTTPS_PROXY="http://cache.net.local:3128"
NO_PROXY="/var/run/docker.sock"
http_proxy=$HTTP_PROXY
https_proxy=$HTTPS_PROXY
no_proxy=$NO_PROXY
export HTTP_PROXY HTTPS_PROXY http_proxy https_proxy no_proxy NO_PROXY
```

No joy.
